// SPDX-FileCopyrightText: Copyright (C) 2024 Adaline Simonian
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This file is part of gdvm.
//
// gdvm is free software: you can redistribute it and/or modify it under the
// terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// gdvm is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
// A PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// this program. If not, see <https://www.gnu.org/licenses/>.

use std::fs;
use std::io::Write;
use std::path::Path;

use anyhow::{Result, anyhow};

use crate::t;

/// Write data to a file atomically by writing to a temp file in the same
/// directory and then renaming it to the target path.
pub fn atomic_write(path: &Path, data: &str) -> Result<()> {
    let parent = path
        .parent()
        .ok_or_else(|| anyhow!(t!("error-invalid-path", path = path.display().to_string())))?;

    fs::create_dir_all(parent)?;

    let mut tmp = tempfile::NamedTempFile::new_in(parent)?;
    tmp.write_all(data.as_bytes())?;
    tmp.as_file().sync_all()?;
    tmp.persist(path)?;

    Ok(())
}

/// Header written to the top of marker files.
pub const MARKER_FILE_HEADER: &str = "## DO NOT EDIT THIS FILE! ##\n\
## THIS FILE IS AUTOMATICALLY MANAGED BY GDVM. ##\n\
## EDITING IT CAN BREAK YOUR GDVM CONFIGURATION ##\n";

/// Read the first line, excluding comments and empty lines, from a marker file.
pub fn read_marker_line(path: &Path) -> Result<Option<String>> {
    if !path.exists() {
        return Ok(None);
    }

    let contents = fs::read_to_string(path)?;
    Ok(contents
        .lines()
        .map(str::trim)
        .find(|line| !line.is_empty() && !line.starts_with('#'))
        .map(str::to_string))
}

/// Write `value` to a marker file.
pub fn write_marker_line(path: &Path, value: &str) -> Result<()> {
    atomic_write(path, &format!("{MARKER_FILE_HEADER}{value}\n"))?;
    Ok(())
}

/// Turn a byte count into a (value, unit) tuple for formatting.
pub fn byte_display_args(bytes: u64) -> (f64, &'static str) {
    const UNITS: [&str; 5] = ["b", "kib", "mib", "gib", "tib"];
    let mut value = bytes as f64;
    let mut unit = 0;

    while value >= 1024.0 && unit < UNITS.len() - 1 {
        value /= 1024.0;
        unit += 1;
    }
    (value, UNITS[unit])
}

/// Compute the approximate size of a file or directory in bytes.
pub fn dir_size(path: &Path) -> u64 {
    let Ok(meta) = std::fs::symlink_metadata(path) else {
        return 0;
    };

    if meta.file_type().is_symlink() {
        return 0;
    }

    if meta.is_file() {
        return meta.len();
    }

    let mut total = 0;

    if let Ok(entries) = std::fs::read_dir(path) {
        for entry in entries.flatten() {
            total += dir_size(&entry.path());
        }
    }
    total
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn atomic_write_creates_parent_and_overwrites() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let path = dir.path().join("nested").join("cache.json");

        atomic_write(&path, "first")?;
        assert_eq!(fs::read_to_string(&path)?, "first");

        atomic_write(&path, "second")?;
        assert_eq!(fs::read_to_string(&path)?, "second");

        Ok(())
    }

    #[test]
    fn read_marker_line_skips_comments_and_empty_lines() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let path = dir.path().join("marker");

        atomic_write(&path, "# comment\n\nvalue\n")?;
        assert_eq!(read_marker_line(&path)?, Some("value".to_string()));

        atomic_write(&path, "# comment\n\n# another comment\n\n")?;
        assert_eq!(read_marker_line(&path)?, None);

        Ok(())
    }

    #[test]
    fn write_marker_line_writes_header() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let path = dir.path().join("marker");

        write_marker_line(&path, "value")?;

        let contents = fs::read_to_string(&path)?;

        assert!(contents.starts_with(MARKER_FILE_HEADER));
        assert!(contents.contains("value"));

        Ok(())
    }
}
