// SPDX-FileCopyrightText: Copyright (C) 2024 Adaline Simonian
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This file is part of gdvm.
//
// gdvm is free software: you can redistribute it and/or modify it under the
// terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// gdvm is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
// A PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// this program. If not, see <https://www.gnu.org/licenses/>.

use crate::{eprintln_i18n, i18n::I18n};
use anyhow::Result;
use std::fs;
#[cfg(target_family = "unix")]
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

#[cfg(target_os = "windows")]
const GDVM_SHIM: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/shim.exe"));
#[cfg(not(target_os = "windows"))]
const GDVM_SHIM: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/shim"));

const HEADER: &str = "## DO NOT EDIT THIS FILE! ##\n\
## THIS FILE IS AUTOMATICALLY MANAGED BY GDVM. ##\n\
## EDITING IT CAN BREAK YOUR GDVM CONFIGURATION ##\n";

type MigrationFn = fn(&Path, &I18n) -> Result<()>;

struct Migration {
    version: u32,
    run: MigrationFn,
}

macro_rules! define_migrations {
    ( $( $ver:literal => |$path:ident, $i18n:ident| $body:block ),* $(,)? ) => {
        const MIGRATIONS: &[Migration] = &[
            $( Migration { version: $ver, run: |$path, $i18n| -> Result<()> { $body } }, )*
        ];
    };
}

define_migrations! {
    1 => |base_path, i18n| {
        let bin_path = base_path.join("bin");

        fs::create_dir_all(&bin_path)?;

        let targets: &[&str] = if cfg!(target_os = "windows") {
            &["godot.exe", "godot_console.exe"]
        } else {
            &["godot"]
        };

        for exe in targets {
            let exe_path = bin_path.join(exe);
            if let Err(err) = write_bytes_if_different(GDVM_SHIM, &exe_path, Some(0o755)) {
                eprintln_i18n!(
                    i18n,
                    "error-ensure-godot-binaries-failed",
                    error = &err.to_string(),
                    path = &exe_path.to_string_lossy().to_string(),
                );
                return Err(err);
            }
        }

        Ok(())
    },
    2 => |base_path, i18n| {
        // Migrate install directories from flat layout to variant subfolder
        // layout, so every build lives under a variant dir:
        //
        //   4.4.1-stable-csharp/  moves to  csharp/4.4.1-stable/
        //   4.4.1-stable/         moves to  default/4.4.1-stable/
        //
        // Create a symlink from the old path to the new path for backward
        // compatibility with existing links. Silently warn on symlink failure.
        let installs = base_path.join("installs");

        if !installs.is_dir() {
            return Ok(());
        }

        let entries: Vec<PathBuf> = fs::read_dir(&installs)?
            .filter_map(|e| e.ok())
            .filter(|e| {
                // Only process real directories, not symlinks from a previous migration.
                e.metadata().map(|m| m.is_dir()).unwrap_or(false)
                    && !e.file_type().map(|t| t.is_symlink()).unwrap_or(false)
            })
            .map(|e| e.path())
            .collect();

        for old_path in entries {
            let dir_name = match old_path.file_name().and_then(|n| n.to_str()) {
                Some(n) => n.to_string(),
                None => continue,
            };

            let new_path = if let Some(base) = dir_name.strip_suffix("-csharp") {
                installs.join("csharp").join(base)
            } else if crate::version_utils::GodotVersion::from_install_str(&dir_name).is_ok() {
                installs
                    .join(crate::version_utils::DEFAULT_VARIANT)
                    .join(&dir_name)
            } else {
                // Not a recognized install, ignore.
                continue;
            };

            if new_path.exists() {
                continue;
            }

            if let Some(parent) = new_path.parent() {
                fs::create_dir_all(parent)?;
            }

            // Don't error if the user ran gdvm twice and the other instance
            // already got rid of the path.
            match fs::rename(&old_path, &new_path) {
                Ok(()) => {}
                Err(e) if e.kind() == std::io::ErrorKind::NotFound => continue,
                Err(e) => return Err(e.into()),
            }

            if let Err(err) = create_symlink(&new_path, &old_path) {
                eprintln_i18n!(
                    i18n,
                    "error-link-symlink",
                    target = &old_path.to_string_lossy().to_string(),
                    link = &new_path.to_string_lossy().to_string(),
                    error = &err.to_string(),
                );
            }
        }

        Ok(())
    }
}

pub fn run_migrations(base_path: &Path, i18n: &I18n) -> Result<()> {
    fs::create_dir_all(base_path)?;

    let version_file = base_path.join("data_version");
    let original_version = read_data_version(&version_file)?;
    let mut current = original_version;

    for mig in MIGRATIONS {
        if current < mig.version {
            (mig.run)(base_path, i18n)?;
            current = mig.version;
        }
    }

    if original_version == current {
        return Ok(());
    }

    write_data_version(&version_file, current)?;

    Ok(())
}

fn read_data_version(path: &Path) -> Result<u32> {
    if !path.exists() {
        return Ok(0);
    }

    let contents = fs::read_to_string(path)?;

    for line in contents.lines() {
        let trimmed = line.trim();

        if trimmed.starts_with('#') || trimmed.is_empty() {
            continue;
        }

        if let Ok(v) = trimmed.parse::<u32>() {
            return Ok(v);
        }
    }
    Ok(0)
}

fn write_data_version(path: &Path, version: u32) -> Result<()> {
    let content = format!("{HEADER}{version}\n");

    fs::write(path, content)?;

    Ok(())
}

fn write_bytes_if_different(bytes: &[u8], dest: &Path, perm: Option<u32>) -> Result<()> {
    #[cfg(not(target_family = "unix"))]
    let _ = perm;

    let write_bytes = || -> Result<()> {
        fs::write(dest, bytes)?;

        #[cfg(target_family = "unix")]
        if let Some(mode) = perm {
            fs::set_permissions(dest, fs::Permissions::from_mode(mode))?;
        }

        Ok(())
    };

    if let Ok(metadata) = fs::metadata(dest) {
        if metadata.len() != bytes.len() as u64 {
            write_bytes()?;
        }
    } else {
        write_bytes()?;
    }

    let file = fs::File::open(dest)?;
    let mut reader = std::io::BufReader::new(file);
    let mut idx = 0;
    let mut buffer = [0u8; 8192];

    loop {
        let read = std::io::Read::read(&mut reader, &mut buffer)?;

        if read == 0 {
            break;
        }

        if buffer[..read] != bytes[idx..idx + read] {
            write_bytes()?;
            return Ok(());
        }

        idx += read;
    }

    Ok(())
}

#[cfg(target_family = "unix")]
fn create_symlink(target: &Path, link: &Path) -> std::io::Result<()> {
    std::os::unix::fs::symlink(target, link)
}

#[cfg(target_family = "windows")]
fn create_symlink(target: &Path, link: &Path) -> std::io::Result<()> {
    std::os::windows::fs::symlink_dir(target, link)
}
