# SPDX-FileCopyrightText: Copyright (C) 2024 Adaline Simonian
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of gdvm.
#
# gdvm is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# gdvm is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.

version = 1

[[annotations]]
path = [
    ".prettierrc",
    "**/.prettierignore",
    ".vscode/**",
    "**/*.json",
    "Cargo.lock",
    "gh-pages/*.webmanifest",
    "gh-pages/robots.txt",
]
SPDX-FileCopyrightText = "Copyright (C) 2024 Adaline Simonian"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
    "gh-pages/*.png",
    "gh-pages/*.ico",
    "gh-pages/favicon.svg",
    "gh-pages/gdvm-textmark.svg",
    "gh-pages/logo.svg",
]
SPDX-FileCopyrightText = "Copyright (C) 2024 Adaline Simonian"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = ["gh-pages/index.html"]
SPDX-FileCopyrightText = "Copyright (C) 2024 Adaline Simonian"
SPDX-License-Identifier = "CC-BY-SA-4.0 AND GPL-3.0-or-later"

[[annotations]]
path = ["gh-pages/inter/**"]
SPDX-FileCopyrightText = "Copyright (c) 2016 The Inter Project Authors"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = ["gh-pages/bluesky-logo.svg"]
SPDX-FileCopyrightText = "Copyright Bluesky, PBC"
SPDX-License-Identifier = "LicenseRef-trademarked"

[[annotations]]
path = ["gh-pages/github-logo.svg"]
SPDX-FileCopyrightText = "Copyright GitHub, Inc."
SPDX-License-Identifier = "LicenseRef-trademarked"

[[annotations]]
path = ["gh-pages/gdvm-godot.svg"]
SPDX-FileCopyrightText = [
    "Copyright (C) 2024 Adaline Simonian",
    "Copyright 2017 Andrea Calabró",
]
SPDX-License-Identifier = "CC-BY-SA-4.0 AND CC-BY-4.0"
