// SPDX-FileCopyrightText: Copyright (C) 2024 Adaline Simonian
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This file is part of gdvm.
//
// gdvm is free software: you can redistribute it and/or modify it under the
// terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// gdvm is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
// A PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// this program. If not, see <https://www.gnu.org/licenses/>.

use clap::{Arg, ArgAction, Command, value_parser};
use gdvm::config::{self};
use gdvm::t;
use gdvm::version::{self};

fn refresh_flag() -> Arg {
    Arg::new("refresh")
        .long("refresh")
        .num_args(0)
        .help(t!("help-refresh-flag"))
}

fn format_flag() -> Arg {
    Arg::new("format")
        .long("format")
        .value_parser(["text", "json"])
        .default_value("text")
        .help(t!("help-format"))
}

fn yes_flag() -> Arg {
    Arg::new("yes")
        .short('y')
        .long("yes")
        .num_args(0)
        .help(t!("help-yes"))
}

fn include_pre_flag() -> Arg {
    Arg::new("include-pre")
        .long("include-pre")
        .visible_alias("pre")
        .short('p')
        .num_args(0)
        .help(t!("help-include-pre"))
}

fn deprecated_csharp_flag() -> Arg {
    Arg::new("csharp")
        .long("csharp")
        .action(ArgAction::SetTrue)
        .hide(true)
        .help(t!("help-csharp"))
}

fn deprecated_csharp_flag_with_value() -> Arg {
    Arg::new("csharp")
        .long("csharp")
        .value_parser(value_parser!(bool))
        .num_args(0..=1)
        .default_missing_value("true")
        .default_value("false")
        .require_equals(true)
        .hide(true)
        .help(t!("help-csharp"))
        .long_help(t!("help-run-csharp-long"))
}

/// Build the gdvm command-line interface.
pub(crate) fn build_cli() -> Command {
    Command::new("gdvm")
        .version(env!("CARGO_PKG_VERSION"))
        .author("Adaline Simonian <adalinesimonian@gmail.com>")
        .about(t!("help-about"))
        .subcommand_required(true)
        .arg_required_else_help(true)
        .disable_help_flag(true)
        .disable_version_flag(true)
        .disable_help_subcommand(true)
        .max_term_width(100)
        .arg(
            Arg::new("help")
                .short('h')
                .long("help")
                .action(clap::ArgAction::Help)
                .global(true)
                .help(t!("help-help")),
        )
        .arg(
            Arg::new("version")
                .short('V')
                .long("version")
                .action(clap::ArgAction::Version)
                .help(t!("help-gdvm-version")),
        )
        .subcommand(
            Command::new("install")
                .about(t!("help-install"))
                .arg(
                    Arg::new("version")
                        .required(true)
                        .value_parser(version::validate_version_spec)
                        .help(t!("help-version"))
                        .long_help(t!("help-version-long")),
                )
                .arg(
                    Arg::new("force")
                        .long("force")
                        .short('f')
                        .num_args(0)
                        .help(t!("help-force")),
                )
                .arg(
                    Arg::new("redownload")
                        .long("redownload")
                        .num_args(0)
                        .help(t!("help-redownload")),
                )
                .arg(deprecated_csharp_flag())
                .arg(include_pre_flag())
                .arg(refresh_flag())
                .arg(yes_flag()),
        )
        .subcommand(
            Command::new("diagnose")
                .about(t!("help-diagnose"))
                .arg(format_flag()),
        )
        .subcommand(
            Command::new("list")
                .about(t!("help-list"))
                .arg(format_flag()),
        )
        .subcommand(
            Command::new("run")
                .about(t!("help-run"))
                .arg(
                    Arg::new("version")
                        .required(false)
                        .value_parser(version::validate_version_spec)
                        .help(t!("help-version-installed")),
                )
                .arg(
                    Arg::new("console")
                        .short('c')
                        .long("console")
                        .value_parser(value_parser!(bool))
                        .num_args(0..=1)
                        .default_missing_value("true")
                        .default_value(
                            #[cfg(target_os = "windows")]
                            "false",
                            #[cfg(not(target_os = "windows"))]
                            "true",
                        )
                        .require_equals(true)
                        .help(t!("help-console")),
                )
                .arg(
                    Arg::new("force")
                        .long("force")
                        .short('f')
                        .num_args(0)
                        .help(t!("help-run-force"))
                        .long_help(t!("help-run-force-long")),
                )
                // Allow any number of command line arguments to be passed to the Godot executable after "--"
                .arg(
                    Arg::new("args")
                        .num_args(0..)
                        .last(true)
                        .help(t!("help-run-args")),
                )
                .arg(deprecated_csharp_flag_with_value())
                .arg(include_pre_flag())
                .arg(refresh_flag())
                .arg(yes_flag()),
        )
        .subcommand(
            Command::new("show")
                .about(t!("help-show"))
                .arg(format_flag())
                .arg(
                    Arg::new("version")
                        .required(false)
                        .value_parser(version::validate_version_spec)
                        .help(t!("help-version-installed")),
                )
                .arg(
                    Arg::new("console")
                        .short('c')
                        .long("console")
                        .value_parser(value_parser!(bool))
                        .num_args(0..=1)
                        .default_missing_value("true")
                        .default_value(
                            #[cfg(target_os = "windows")]
                            "false",
                            #[cfg(not(target_os = "windows"))]
                            "true",
                        )
                        .require_equals(true)
                        .help(t!("help-console")),
                )
                .arg(
                    Arg::new("force")
                        .long("force")
                        .short('f')
                        .num_args(0)
                        .help(t!("help-run-force"))
                        .long_help(t!("help-run-force-long")),
                )
                .arg(deprecated_csharp_flag_with_value())
                .arg(include_pre_flag())
                .arg(refresh_flag())
                .arg(yes_flag()),
        )
        .subcommand(
            Command::new("info")
                .about(t!("help-info"))
                .arg(format_flag())
                .arg(
                    Arg::new("version")
                        .required(false)
                        .value_parser(version::validate_version_spec)
                        .help(t!("help-version-installed")),
                )
                .arg(include_pre_flag()),
        )
        .subcommand(
            Command::new("cache-path")
                .about(t!("help-cache-path"))
                .arg(format_flag())
                .arg(
                    Arg::new("version")
                        .required(true)
                        .value_parser(version::validate_version_spec)
                        .help(t!("help-version")),
                )
                .arg(deprecated_csharp_flag_with_value())
                .arg(include_pre_flag())
                .arg(refresh_flag())
                .arg(yes_flag()),
        )
        .subcommand(
            Command::new("link")
                .about(t!("help-link"))
                .override_usage("gdvm link [OPTIONS] [version] <linkpath>")
                .allow_missing_positional(true)
                .arg(
                    Arg::new("version")
                        .required(false)
                        .value_parser(version::validate_version_spec)
                        .help(t!("help-link-version")),
                )
                .arg({
                    let platform = {
                        #[cfg(target_os = "windows")]
                        {
                            "windows"
                        }
                        #[cfg(target_os = "macos")]
                        {
                            "macos"
                        }
                        #[cfg(all(not(target_os = "windows"), not(target_os = "macos")))]
                        {
                            "other"
                        }
                    };

                    Arg::new("linkpath")
                        .required(true)
                        .value_name("linkpath")
                        .help(t!("help-link-path", platform = platform))
                })
                .arg(
                    Arg::new("force")
                        .long("force")
                        .short('f')
                        .num_args(0)
                        .help(t!("help-link-force")),
                )
                .arg(
                    Arg::new("copy")
                        .long("copy")
                        .num_args(0)
                        .help(t!("help-link-copy")),
                )
                .arg(deprecated_csharp_flag_with_value())
                .arg(yes_flag()),
        )
        .subcommand(
            Command::new("remove")
                .about(t!("help-remove"))
                .arg(
                    Arg::new("version")
                        .required(true)
                        .value_parser(version::validate_version_spec)
                        .help(t!("help-version-installed")),
                )
                .arg(
                    Arg::new("yes")
                        .short('y')
                        .long("yes")
                        .num_args(0)
                        .help(t!("help-remove-yes-deprecated")),
                )
                .arg(deprecated_csharp_flag()),
        )
        .subcommand(
            Command::new("search")
                .about(t!("help-search"))
                .arg(format_flag())
                .arg(Arg::new("filter").required(false).help(t!("help-filter")))
                .arg(
                    Arg::new("filter-deprecated")
                        .long("filter")
                        .num_args(1)
                        .help(t!("help-filter-deprecated")),
                )
                .arg(
                    Arg::new("include-pre")
                        .long("include-pre")
                        .visible_alias("pre")
                        .short('p')
                        .num_args(0)
                        .help(t!("help-include-pre")),
                )
                .arg(
                    Arg::new("cache-only")
                        .long("cache-only")
                        .num_args(0)
                        .help(t!("help-cache-only")),
                )
                .arg(
                    Arg::new("limit")
                        .long("limit")
                        .num_args(1)
                        .default_value("10")
                        .value_parser(clap::value_parser!(usize))
                        .help(t!("help-limit")),
                )
                .arg(refresh_flag())
                .arg(yes_flag()),
        )
        .subcommand(Command::new("clear-cache").about(t!("help-clear-cache")))
        .subcommand(Command::new("refresh").about(t!("help-refresh")))
        .subcommand(
            Command::new("prune")
                .about(t!("help-prune"))
                .arg(format_flag())
                .long_about(t!(
                    "help-prune-long",
                    default_days = config::DEFAULT_PRUNE_MAX_AGE_DAYS
                ))
                .arg(
                    Arg::new("all")
                        .long("all")
                        .short('a')
                        .num_args(0)
                        .help(t!("help-prune-all")),
                )
                .arg(
                    Arg::new("force")
                        .long("force")
                        .short('f')
                        .num_args(0)
                        .help(t!("help-prune-force")),
                )
                .arg(
                    Arg::new("dry-run")
                        .long("dry-run")
                        .num_args(0)
                        .help(t!("help-prune-dry-run")),
                ),
        )
        .subcommand(
            Command::new("use")
                .about(t!("help-default"))
                .arg(
                    Arg::new("version")
                        .help(t!("help-default-version"))
                        .required(false),
                )
                .arg(deprecated_csharp_flag())
                .arg(include_pre_flag())
                .arg(refresh_flag())
                .arg(yes_flag()),
        )
        .subcommand(
            Command::new("upgrade")
                .about(t!("help-upgrade"))
                .arg(
                    Arg::new("major")
                        .long("major")
                        .short('m')
                        .num_args(0)
                        .help(t!("help-upgrade-major")),
                )
                .arg(
                    Arg::new("pre")
                        .long("pre")
                        .short('p')
                        .num_args(0)
                        .help(t!("help-upgrade-pre")),
                ),
        )
        .subcommand(
            Command::new("pin")
                .about(t!("help-pin"))
                .long_about(t!("help-pin-long"))
                .arg(
                    Arg::new("version")
                        .help(t!("help-pin-version"))
                        .required(true),
                )
                .arg(deprecated_csharp_flag())
                .arg(include_pre_flag())
                .arg(refresh_flag())
                .arg(
                    Arg::new("no-legacy")
                        .long("no-legacy")
                        .num_args(0)
                        .help(t!("help-no-legacy")),
                )
                .arg(yes_flag()),
        )
        .subcommand(
            Command::new("config")
                .about(t!("help-config"))
                .subcommand(
                    Command::new("get")
                        .about(t!("help-config-get"))
                        .arg(format_flag())
                        .arg(Arg::new("key").required(true).help(t!("help-config-key"))),
                )
                .subcommand(
                    Command::new("set")
                        .about(t!("help-config-set"))
                        .arg(Arg::new("key").required(true).help(t!("help-config-key")))
                        .arg(
                            Arg::new("value")
                                .required(false)
                                .help(t!("help-config-value")),
                        ),
                )
                .subcommand(
                    Command::new("unset").about(t!("help-config-unset")).arg(
                        Arg::new("key")
                            .required(true)
                            .help(t!("help-config-unset-key")),
                    ),
                )
                .subcommand(
                    Command::new("list")
                        .about(t!("help-config-list"))
                        .arg(
                            Arg::new("show-sensitive")
                                .long("show-sensitive")
                                .action(clap::ArgAction::SetTrue)
                                .help(t!("help-config-show-sensitive")),
                        )
                        .arg(
                            Arg::new("available")
                                .long("available")
                                .short('a')
                                .action(clap::ArgAction::SetTrue)
                                .help(t!("help-config-available")),
                        ),
                ),
        )
        .subcommand(
            Command::new("registry")
                .about(t!("help-registry"))
                .subcommand_required(true)
                .arg_required_else_help(true)
                .subcommand(
                    Command::new("add")
                        .about(t!("help-registry-add"))
                        .arg(
                            Arg::new("name")
                                .required(true)
                                .help(t!("help-registry-name")),
                        )
                        .arg(Arg::new("url").required(true).help(t!("help-registry-url"))),
                )
                .subcommand(
                    Command::new("remove")
                        .about(t!("help-registry-remove"))
                        .arg(
                            Arg::new("name")
                                .required(true)
                                .help(t!("help-registry-name")),
                        ),
                )
                .subcommand(
                    Command::new("list")
                        .about(t!("help-registry-list"))
                        .arg(format_flag()),
                )
                .subcommand(
                    Command::new("refresh")
                        .about(t!("help-registry-refresh"))
                        .arg(
                            Arg::new("name")
                                .required(false)
                                .help(t!("help-registry-name")),
                        ),
                )
                .subcommand(
                    Command::new("init")
                        .about(t!("help-registry-init"))
                        .arg(Arg::new("dir").required(true).help(t!("help-registry-dir")))
                        .arg(
                            Arg::new("name")
                                .long("name")
                                .num_args(1)
                                .help(t!("help-registry-init-name")),
                        ),
                )
                .subcommand(
                    Command::new("add-build")
                        .about(t!("help-registry-add-build"))
                        .arg(Arg::new("dir").required(true).help(t!("help-registry-dir")))
                        .arg(
                            Arg::new("version")
                                .long("version")
                                .num_args(1)
                                .required(true)
                                .help(t!("help-registry-build-version")),
                        )
                        .arg(
                            Arg::new("variant")
                                .long("variant")
                                .num_args(1)
                                .help(t!("help-registry-build-variant")),
                        )
                        .arg(
                            Arg::new("platform")
                                .long("platform")
                                .num_args(1)
                                .required(true)
                                .help(t!("help-registry-build-platform")),
                        )
                        .arg(
                            Arg::new("file")
                                .long("file")
                                .num_args(1)
                                .required(false)
                                .help(t!("help-registry-build-file")),
                        )
                        .arg(
                            Arg::new("store")
                                .long("store")
                                .num_args(0)
                                .help(t!("help-registry-build-store")),
                        )
                        .arg(
                            Arg::new("url")
                                .long("url")
                                .num_args(1)
                                .conflicts_with("store")
                                .help(t!("help-registry-build-url")),
                        )
                        .arg(
                            Arg::new("sha512")
                                .long("sha512")
                                .num_args(1)
                                .help(t!("help-registry-build-sha512")),
                        )
                        .arg(
                            Arg::new("size")
                                .long("size")
                                .num_args(1)
                                .value_parser(value_parser!(u64))
                                .help(t!("help-registry-build-size")),
                        ),
                )
                .subcommand(
                    Command::new("remove-build")
                        .about(t!("help-registry-remove-build"))
                        .arg(Arg::new("dir").required(true).help(t!("help-registry-dir")))
                        .arg(
                            Arg::new("version")
                                .long("version")
                                .num_args(1)
                                .required(true)
                                .help(t!("help-registry-build-version")),
                        )
                        .arg(
                            Arg::new("variant")
                                .long("variant")
                                .num_args(1)
                                .help(t!("help-registry-build-variant")),
                        )
                        .arg(
                            Arg::new("platform")
                                .long("platform")
                                .num_args(1)
                                .help(t!("help-registry-build-platform")),
                        ),
                )
                .subcommand(
                    Command::new("validate")
                        .about(t!("help-registry-validate"))
                        .arg(Arg::new("dir").required(true).help(t!("help-registry-dir"))),
                ),
        )
        .subcommand(
            Command::new("completions")
                .about(t!("help-completions"))
                .arg(
                    Arg::new("shell")
                        .required(true)
                        .value_parser(clap::value_parser!(clap_complete::Shell))
                        .help(t!("help-completions-shell")),
                ),
        )
}
