// SPDX-FileCopyrightText: Copyright (C) 2024 Adaline Simonian
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This file is part of gdvm.
//
// gdvm is free software: you can redistribute it and/or modify it under the
// terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// gdvm is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
// A PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// this program. If not, see <https://www.gnu.org/licenses/>.

use std::path::{Path, PathBuf};
use std::process::Command;
use std::{env, fs};

fn main() {
    let target = env::var("TARGET").unwrap();
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir.parent().unwrap().parent().unwrap();
    let shim_name = if target.contains("windows") {
        "shim.exe"
    } else {
        "shim"
    };

    generate_status_label_widths(&manifest_dir, &out_dir);

    println!("cargo:rerun-if-env-changed=GDVM_PREBUILT_SHIM");
    if let Ok(prebuilt) = env::var("GDVM_PREBUILT_SHIM") {
        fs::copy(&prebuilt, out_dir.join(shim_name)).expect("failed to copy prebuilt shim binary");
        println!("cargo:rerun-if-changed={prebuilt}");
        return;
    }

    let status = Command::new("cargo")
        .arg("build")
        .arg("--release")
        .arg("--target")
        .arg(&target)
        // Build shim as standalone package to avoid workspace lock.
        .arg("--manifest-path")
        .arg(
            workspace_root
                .join("crates")
                .join("shim")
                .join("Cargo.toml"),
        )
        .arg("--target-dir")
        .arg(workspace_root.join("intermediate"))
        .status()
        .expect("failed to build shim");

    assert!(status.success());

    let shim_source = workspace_root
        .join("intermediate")
        .join(&target)
        .join("release")
        .join(shim_name);
    let shim_dest = out_dir.join(shim_name);
    fs::copy(&shim_source, &shim_dest).expect("failed to copy shim binary");

    println!("cargo:rerun-if-changed=../shim/src/main.rs");
    println!("cargo:rerun-if-changed=../shim/Cargo.toml");
}

/// Precompute a map of locale to the display width of the longest status label in that locale.
fn generate_status_label_widths(manifest_dir: &Path, out_dir: &Path) {
    use std::collections::BTreeMap;

    use fluent_syntax::{ast, parser};

    let i18n_dir = manifest_dir.join("i18n");
    let mut widths: BTreeMap<String, usize> = BTreeMap::new();

    println!("cargo:rerun-if-changed={}", i18n_dir.display());

    if let Ok(entries) = fs::read_dir(&i18n_dir) {
        for entry in entries {
            let path = entry.expect("failed to read i18n entry").path();

            if path.extension().and_then(|ext| ext.to_str()) != Some("ftl") {
                continue;
            }

            let Some(locale) = path.file_stem().and_then(|stem| stem.to_str()) else {
                continue;
            };
            let contents = fs::read_to_string(&path).expect("failed to read translation bundle");

            let resource =
                parser::parse(contents.as_str()).unwrap_or_else(|(resource, _)| resource);

            let max = resource
                .body
                .iter()
                .filter_map(|entry| match entry {
                    ast::Entry::Message(message) => Some(message),
                    _ => None,
                })
                .filter(|message| message.id.name.starts_with("status-"))
                .filter_map(|message| message.value.as_ref())
                .map(fluent_pattern_length)
                .max()
                .unwrap_or(0);

            widths.insert(locale.to_string(), max);
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }

    let fallback = widths.get("en-US").copied().unwrap_or(12);
    let mut generated = String::from("// @generated by build.rs. Do not edit.\n");

    generated.push_str("static STATUS_LABEL_WIDTHS: &[(&str, usize)] = &[\n");

    for (locale, width) in &widths {
        generated.push_str(&format!("    ({locale:?}, {width}),\n"));
    }

    generated.push_str("];\n");
    generated.push_str(&format!(
        "const STATUS_LABEL_WIDTH_FALLBACK: usize = {fallback};\n"
    ));

    fs::write(out_dir.join("status_label_widths.rs"), generated)
        .expect("failed to generate status label widths");
}

/// Measure the length of a Fluent pattern.
fn fluent_pattern_length(pattern: &fluent_syntax::ast::Pattern<&str>) -> usize {
    use fluent_syntax::ast::PatternElement;
    use unicode_width::UnicodeWidthStr;

    pattern
        .elements
        .iter()
        .map(|element| match element {
            PatternElement::TextElement { value } => value.width(),
            PatternElement::Placeable { .. } => 0,
        })
        .sum()
}
