name: Main Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            x86_64-unknown-linux-gnu,
            i686-unknown-linux-gnu,
            aarch64-unknown-linux-gnu,
            x86_64-pc-windows-gnu,
            i686-pc-windows-gnu,
            aarch64-pc-windows-gnu,
          ]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build
        run: cross build --release --target ${{ matrix.target }}

      - name: Check i18n
        run: scripts/find-missing-i18n.sh

  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: brew install openssl

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Check i18n
        run: scripts/find-missing-i18n.sh
