name: Validate Registry (v1)

on:
  push:
    branches:
      - registry
  pull_request:
    branches:
      - registry

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout registry
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: "v1/package.json"

      - name: Validate registry
        run: node ./validate.mjs
        working-directory: v1
